version: '3.3'

services:
  database:
    container_name: local-mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: chinese_learning
      MYSQL_USER: thopb
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - tour-network
    restart: always

networks:
  tour-network:
    driver: bridge